---
title: Calculation Servive
---

classDiagram
CalculationService -- ExpenseController

 CalculationService: +CalculationService~Interface~
 CalculationService: +calculateTotalAmount(List~Expense~ expenses)

