---
title: Unpaid Expenses
---

classDiagram
UnpaidExpenses -- ExpenseController

 UnpaidExpenses: -List~Expense~ expenses
 UnpaidExpenses: -double total
 UnpaidExpenses: +setExpenses(List~Expense~ expenses)
 UnpaidExpenses: +setTotal()